# Generated by Django 4.2.1 on 2023-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamLeader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleaderphoto',
            name='img',
            field=models.ImageField(upload_to='Team Leader'),
        ),
    ]
