# Generated by Django 4.2.1 on 2023-07-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamLeader', '0002_alter_teamleaderphoto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleaderphoto',
            name='img',
            field=models.ImageField(upload_to='Leader'),
        ),
    ]
