# Generated by Django 4.2.1 on 2023-07-17 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminModule', '0003_customuserskill_customuserexperience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=11)),
                ('tag', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(choices=[('ABP', 'Al Baraka Bank (Pakistan) Limited'), ('ABL', 'Allied Bank Limited'), ('AB', 'Askari Bank'), ('BAP', 'Bank Alfalah Limited'), ('BAH', 'Bank Al-Habib Limited'), ('BIP', 'BankIslami Pakistan Limited'), ('BOP', 'Bank of Punjab'), ('FBL', 'Faysal Bank Limited'), ('HBL', 'Habib Bank Limited'), ('JS', 'JS Bank Limited'), ('MCB', 'MCB Bank Limited'), ('MBL', 'Meezan Bank Limited'), ('NBP', 'National Bank of Pakistan'), ('SB', 'Summit Bank Pakistan'), ('UBL', 'United Bank Limited (UBL)')], max_length=255)),
                ('AccountNO', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
