# Generated by Django 4.2.1 on 2023-07-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminModule', '0005_leaveapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveApplication',
        ),
    ]
