# Generated by Django 4.2.1 on 2023-07-10 07:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('Partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Partner')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExperiencedField', models.CharField(max_length=255)),
                ('ExperiencedYear', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudyIn', models.CharField(max_length=255)),
                ('PassingYear', models.DateField()),
                ('Partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', tinymce.models.HTMLField()),
                ('Partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(choices=[('ABP', 'Al Baraka Bank (Pakistan) Limited'), ('ABL', 'Allied Bank Limited'), ('AB', 'Askari Bank'), ('BAP', 'Bank Alfalah Limited'), ('BAH', 'Bank Al-Habib Limited'), ('BIP', 'BankIslami Pakistan Limited'), ('BOP', 'Bank of Punjab'), ('FBL', 'Faysal Bank Limited'), ('HBL', 'Habib Bank Limited'), ('JS', 'JS Bank Limited'), ('MCB', 'MCB Bank Limited'), ('MBL', 'Meezan Bank Limited'), ('NBP', 'National Bank of Pakistan'), ('SB', 'Summit Bank Pakistan'), ('UBL', 'United Bank Limited (UBL)')], max_length=255)),
                ('AccountNO', models.IntegerField()),
                ('Partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.coordinator')),
            ],
        ),
    ]
