# Generated by Django 4.2.1 on 2023-07-10 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_coordinatorskill_coordinatorphoto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinatorbankdetail',
            old_name='Partner',
            new_name='coordinator',
        ),
        migrations.RenameField(
            model_name='coordinatorbio',
            old_name='Partner',
            new_name='coordinator',
        ),
        migrations.RenameField(
            model_name='coordinatoreducation',
            old_name='Partner',
            new_name='coordinator',
        ),
        migrations.RenameField(
            model_name='coordinatorexperience',
            old_name='Partner',
            new_name='coordinator',
        ),
        migrations.RenameField(
            model_name='coordinatorphoto',
            old_name='partner',
            new_name='coordinator',
        ),
        migrations.RenameField(
            model_name='coordinatorskill',
            old_name='Partner',
            new_name='coordinator',
        ),
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=11)),
                ('tag', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.coordinator')),
            ],
        ),
    ]
