# Generated by Django 4.2.1 on 2023-07-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_rename_partner_coordinatorbankdetail_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorphoto',
            name='img',
            field=models.ImageField(upload_to='coordinator'),
        ),
    ]
