# Generated by Django 4.2.1 on 2023-07-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='team_captain',
            new_name='team',
        ),
    ]
