# Generated by Django 4.2.1 on 2023-07-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssessmentName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstitutionName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('course_code', models.CharField(max_length=10)),
                ('instruction', models.CharField(max_length=126)),
                ('word_count', models.IntegerField()),
                ('attachment_file', models.FileField(upload_to='task')),
                ('task_status', models.CharField(choices=[('Pending', 'Pending'), ('Do Able', 'Do Able'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Working', 'Working'), ('Delivered', 'Delivered')], default='Pending', max_length=25, null=True)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captain.assessmenttype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('institution_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captain.institutionname')),
                ('send_to', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='team.member')),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captain.taskcategory')),
            ],
        ),
    ]
