# Generated by Django 4.2.1 on 2023-07-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartnerModule', '0002_coordinator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinator',
        ),
    ]
